// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: 05

#include "ui.h"
#include "ui_helpers.h"

/*---------------------------------------------------------------
 * Generated UI state
 * SquareLine Studio stores screen objects and initial actions here.
 *--------------------------------------------------------------*/

// Holds the generated object used for initial UI actions.
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

// The exported image data requires the same RGB565 color depth as the project.
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

/**
 * @brief Create the generated theme and first screen.
 *
 * setup() calls this function after LVGL display and input registration.
 *
 * @param None.
 * @return None.
 */
void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}

/**
 * @brief Release all generated screen objects.
 *
 * Call this function when the UI is no longer needed or before rebuilding it.
 *
 * @param None.
 * @return None.
 */
void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
}
