// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: 05

#ifndef _05_UI_H
#define _05_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// Generated screen declarations.

#include "ui_Screen1.h"

// Generated event state.
extern lv_obj_t * ui____initial_actions0;

// Dashboard background exported from assets/background.png.
LV_IMG_DECLARE(ui_img_background_png);

// Generated UI lifecycle entry points.
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
