// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: 05

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_TempLabel1 = NULL;
lv_obj_t * ui_HumiLabel2 = NULL;

/**
 * @brief Build the temperature and humidity screen.
 *
 * ui_init() calls this function once to create the background image and the
 * two labels updated by the main lesson loop.
 *
 * @param None.
 * @return None.
 */
void ui_Screen1_screen_init(void)
{
    /*---------------------------------------------------------------
     * Create the screen and its background image
     * The image provides the fixed dashboard artwork beneath the labels.
     *--------------------------------------------------------------*/
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_background_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);

    /*---------------------------------------------------------------
     * Create the live sensor labels
     * Their positions align the numeric readings with the dashboard art.
     *--------------------------------------------------------------*/
    ui_TempLabel1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TempLabel1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TempLabel1, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_TempLabel1, -30);
    lv_obj_set_y(ui_TempLabel1, -47);
    lv_obj_set_align(ui_TempLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel1, "25");
    lv_obj_set_style_text_color(ui_TempLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiLabel2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HumiLabel2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_HumiLabel2, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_HumiLabel2, -30);
    lv_obj_set_y(ui_HumiLabel2, 31);
    lv_obj_set_align(ui_HumiLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumiLabel2, "50");
    lv_obj_set_style_text_color(ui_HumiLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumiLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumiLabel2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

/**
 * @brief Delete the screen and clear its object references.
 *
 * ui_destroy() calls this function when the generated interface is removed.
 *
 * @param None.
 * @return None.
 */
void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // Clear every reference after LVGL deletes the parent screen tree.
    ui_Screen1 = NULL;
    ui_Image1 = NULL;
    ui_TempLabel1 = NULL;
    ui_HumiLabel2 = NULL;

}
