// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: 05

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// Screen lifecycle functions and objects used by the main lesson.
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_TempLabel1;
extern lv_obj_t * ui_HumiLabel2;
// Add lesson-specific screen variables above this boundary.

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
