// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include <stdio.h>
#include "ui.h"
#include "setup_gpio.h"

void Lamp_on(lv_event_t * e)
{
    printf("open led\n");
	gpio_set_level(18, 1);
}

void Lamp_off(lv_event_t * e)
{
    printf("close led\n");
	gpio_set_level(18, 0);
}