#include <Arduino.h>
#include <esp_heap_caps.h>
#include "pins_config.h"
#include "lamp_control.h"
#include "LovyanGFX_Driver.h"
#include <lvgl.h>

#include "ui.h"

/*---------------------------------------------------------------
 * LVGL draw buffer sizing
 * The buffer is sized in display lines so the lesson can balance
 * refresh speed and internal memory usage.
 *--------------------------------------------------------------*/
static constexpr uint32_t DRAW_BUFFER_LINES = 40;
static constexpr uint32_t DRAW_BUFFER_SIZE = LCD_H_RES * DRAW_BUFFER_LINES * sizeof(uint16_t);

// First LVGL draw buffer stored in internal DMA-capable memory.
static uint8_t *buf;

// Second LVGL draw buffer stored in internal DMA-capable memory.
static uint8_t *buf1;

/**
 * @brief Drive the onboard lamp from the generated UI.
 *
 * LVGL event handlers call these functions when the lesson's buttons or
 * switches change state. The helpers keep the light control logic separate
 * from the UI code generated by SquareLine Studio.
 *
 * @param None.
 * @return None.
 */
extern "C" void lamp_set_on(void) {
  digitalWrite(LED_PIN, HIGH);
  Serial.println("LED ON");
}

/**
 * @brief Turn the onboard lamp off from the generated UI.
 *
 * LVGL event handlers call these functions when the lesson's buttons or
 * switches change state. The helpers keep the light control logic separate
 * from the UI code generated by SquareLine Studio.
 *
 * @param None.
 * @return None.
 */
extern "C" void lamp_set_off(void) {
  digitalWrite(LED_PIN, LOW);
  Serial.println("LED OFF");
}

/**
 * @brief Return the current millisecond tick for LVGL.
 *
 * LVGL calls this function through lv_tick_set_cb() so its timers and
 * animations advance using the Arduino millisecond counter.
 *
 * @param None.
 * @return Current uptime in milliseconds.
 */
static uint32_t my_tick(void) {
  return millis();
}

/**
 * @brief Copy rendered LVGL pixels to the LCD.
 *
 * LVGL calls this function whenever part of the screen needs to be refreshed.
 * The callback sends the prepared RGB565 image through LovyanGFX DMA and
 * then releases LVGL to continue rendering.
 *
 * @param display LVGL display object that requested the flush.
 * @param area Pixel area that must be updated.
 * @param pixel_map Rendered pixel buffer supplied by LVGL.
 * @return None.
 */
static void my_disp_flush(lv_display_t *display, const lv_area_t *area, uint8_t *pixel_map) {
  gfx.startWrite();
  gfx.pushImageDMA(area->x1, area->y1, area->x2 - area->x1 + 1, area->y2 - area->y1 + 1,
                   reinterpret_cast<lgfx::rgb565_t *>(pixel_map));
  gfx.waitDMA();
  gfx.endWrite();
  lv_display_flush_ready(display);
}

// Stores the latest raw touch coordinate reported by the touch controller.
uint16_t touchX, touchY;

/**
 * @brief Provide touch coordinates to LVGL.
 *
 * LVGL calls this function when it needs the current pointer state. The raw
 * touch coordinates are converted to the active screen orientation so the UI
 * widgets can receive correct tap and drag positions.
 *
 * @param indev LVGL input device object that requested the read.
 * @param data Output structure filled with touch state and coordinates.
 * @return None.
 */
static void my_touchpad_read(lv_indev_t *indev, lv_indev_data_t *data) {
  (void)indev;
  data->state = LV_INDEV_STATE_REL;
  if (gfx.getTouch(&touchX, &touchY)) {
    data->state = LV_INDEV_STATE_PR;
    data->point.x = constrain(static_cast<int32_t>(LCD_H_RES - 1) - touchX, 0, LCD_H_RES - 1);
    data->point.y = constrain(static_cast<int32_t>(touchY), 0, LCD_V_RES - 1);

    Serial.print("Data x ");
    Serial.println(data->point.x);
    Serial.print("Data y ");
    Serial.println(data->point.y);
  }
}

/**
 * @brief Initialize the lamp, display, touch input, and generated UI.
 *
 * Arduino calls this function once after reset. It prepares the lamp output,
 * starts the display driver, allocates LVGL draw buffers, registers the touch
 * reader, enables the backlight, and creates the lesson UI objects.
 *
 * @param None.
 * @return None.
 */
void setup()
{
  Serial.begin(115200);

  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);

  gfx.init();
  gfx.initDMA();
  gfx.fillScreen(TFT_BLACK);

  lv_init();
  lv_tick_set_cb(my_tick);

  buf = static_cast<uint8_t *>(heap_caps_malloc(DRAW_BUFFER_SIZE, MALLOC_CAP_DMA | MALLOC_CAP_INTERNAL));
  buf1 = static_cast<uint8_t *>(heap_caps_malloc(DRAW_BUFFER_SIZE, MALLOC_CAP_DMA | MALLOC_CAP_INTERNAL));
  if (buf == nullptr || buf1 == nullptr) {
    Serial.println("LVGL draw buffer allocation failed");
    while (true) {
      delay(1000);
    }
  }

  lv_display_t *display = lv_display_create(LCD_H_RES, LCD_V_RES);
  lv_display_set_color_format(display, LV_COLOR_FORMAT_RGB565);
  lv_display_set_flush_cb(display, my_disp_flush);
  lv_display_set_buffers(display, buf, buf1, DRAW_BUFFER_SIZE, LV_DISPLAY_RENDER_MODE_PARTIAL);

  lv_indev_t *input = lv_indev_create();
  lv_indev_set_type(input, LV_INDEV_TYPE_POINTER);
  lv_indev_set_read_cb(input, my_touchpad_read);

  delay(100);

  pinMode(38, OUTPUT);
  digitalWrite(38, HIGH);

  gfx.fillScreen(TFT_BLACK);
  ui_init();

  Serial.println("Setup done");
}

/**
 * @brief Keep LVGL timers, animations, and touch handling running.
 *
 * Arduino calls this function repeatedly after setup() finishes. The return
 * value from lv_timer_handler() is used to keep the loop responsive without
 * wasting time when LVGL does not need immediate work.
 *
 * @param None.
 * @return None.
 */
void loop()
{
  const uint32_t delay_ms = lv_timer_handler();
  delay(constrain(delay_ms, 1UL, 5UL));
}
