// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: 2.4_inch_03

#include "ui.h"
#include "lamp_control.h"

void Lamp_on(lv_event_t * e)
{
    (void)e;
    lamp_set_on();
}

void Lamp_off(lv_event_t * e)
{
    (void)e;
    lamp_set_off();
}
