// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: dht

#include "../ui.h"

void ui_comp_startMeeting_create_hook(lv_obj_t * comp)
{
}
